/* =========================================================================
   Aeris · config.js
   Constantes globais, endpoints e dicionário de traduções (12 idiomas).
   ========================================================================= */

const CONFIG = {
  // Open-Meteo — API gratuita, sem chave necessária
  GEOCODE_URL: 'https://geocoding-api.open-meteo.com/v1/search',
  FORECAST_URL: 'https://api.open-meteo.com/v1/forecast',
  AIR_QUALITY_URL: 'https://air-quality-api.open-meteo.com/v1/air-quality',
  // Arquivo histórico (ERA5) — usado para calcular a média de anos anteriores
  // e comparar "hoje" com a normal climática para a mesma época do ano.
  ARCHIVE_URL: 'https://archive-api.open-meteo.com/v1/archive',
  // Serviço gratuito de geocodificação inversa (sem chave), usado só para
  // obter o nome da cidade a partir de coordenadas do GPS.
  REVERSE_GEOCODE_URL: 'https://api.bigdatacloud.net/data/reverse-geocode-client',

  DEFAULT_CITY: { name: 'Quelimane', country: 'Moçambique', lat: -17.8786, lon: 36.8883, timezone: 'Africa/Maputo' },

  STORAGE_KEYS: {
    settings: 'aeris.settings',
    favorites: 'aeris.favorites',
    recents: 'aeris.recents',
    lastLocation: 'aeris.lastLocation',
    cache: 'aeris.cache',
    lastScreen: 'aeris.lastScreen'
  },

  AUTO_REFRESH_MS: 10 * 60 * 1000,         // 10 minutos (normal)
  AUTO_REFRESH_LOWDATA_MS: 30 * 60 * 1000, // 30 minutos (modo pouco dados)
  CACHE_TTL_MS: 10 * 60 * 1000,
  // Cache "stale" — quando não há ligação, aceitamos dados guardados mesmo
  // fora do prazo normal, até este limite máximo (modo offline mais forte).
  STALE_CACHE_MAX_AGE_MS: 12 * 60 * 60 * 1000, // 12 horas

  // Alerta hiperlocal de chuva (usa dados minutely_15, interpolados fora
  // da América do Norte / Europa Central, mas ainda assim mais finos que
  // a granularidade horária).
  RAIN_PROB_THRESHOLD: 50,       // % de probabilidade para considerar "vai chover"
  RAIN_MIN_MM: 0.1,              // mm mínimos para considerar chuva real
  RAIN_LOOKAHEAD_STEPS: 8,       // 8 x 15min = próximas 2 horas

  // Comparação histórica (normal climática)
  HISTORICAL_YEARS: 10,
  HISTORICAL_WINDOW_DAYS: 4,               // janela de +/- dias à volta da data de hoje, por ano
  HISTORICAL_CACHE_TTL_MS: 7 * 24 * 60 * 60 * 1000, // 7 dias

  // Limiares para o alerta de tempo severo/ciclone (rajadas em km/h)
  ALERT_CYCLONE_GUSTS: 118,   // força de furacão/ciclone (categoria 1 Saffir-Simpson)
  ALERT_SEVERE_GUSTS: 90,
  ALERT_STRONG_GUSTS: 60,

  // Lista de idiomas suportados, com nome nativo para o seletor
  LANGUAGES: [
    { code: 'pt', native: 'Português' },
    { code: 'en', native: 'English' },
    { code: 'es', native: 'Español' },
    { code: 'fr', native: 'Français' },
    { code: 'de', native: 'Deutsch' },
    { code: 'it', native: 'Italiano' },
    { code: 'zh', native: '中文' },
    { code: 'ar', native: 'العربية' },
    { code: 'sw', native: 'Kiswahili' },
    { code: 'ru', native: 'Русский' },
    { code: 'hi', native: 'हिन्दी' },
    { code: 'ja', native: '日本語' },
  ],
};

const I18N = {
  pt: {
    loading: 'A carregar…', splashSub: 'a preparar o seu céu…',
    searchPlaceholder: 'Pesquisar cidade…',
    feelsLike: 'Sensação térmica de',
    next24h: 'Próximas 24 horas', next7d: 'Previsão para 7 dias', details: 'Detalhes',
    tempChart: 'Gráfico de temperatura',
    dataSource: 'Dados fornecidos por Open‑Meteo',
    updatedNow: 'Atualizado agora · toque para atualizar',
    updatedAgo: 'Atualizado há {n} min · toque para atualizar',
    updating: 'A atualizar…', refreshed: 'Dados atualizados', refreshFailed: 'Não foi possível atualizar agora',
    searchTitle: 'Pesquisar', searchSub: 'Encontre o clima de qualquer cidade do mundo',
    recentSearches: 'Pesquisas recentes',
    noRecents: 'Ainda não há pesquisas recentes.',
    nowLabel: 'Agora',
    noData: 'Sem dados',
    favoritesTitle: 'Favoritos', favoritesSub: 'As suas cidades guardadas',
    favEmpty: 'Ainda não tem cidades favoritas.',
    favEmptyHint: 'Toque na estrela no ecrã principal para guardar uma cidade.',
    settingsTitle: 'Configurações', settingsSub: 'Personalize a sua experiência',
    tempUnit: 'Unidade de temperatura', language: 'Idioma', selectLanguage: 'Selecionar idioma',
    theme: 'Tema', themeAuto: 'Auto', themeLight: 'Claro', themeDark: 'Escuro',
    allowLocation: 'Permitir localização', autoRefresh: 'Atualização automática',
    moreFeatures: 'Mais funcionalidades',
    lowDataMode: 'Modo pouco dados', dailyTipsLabel: 'Sugestões diárias',
    clearCache: 'Limpar cache', cacheCleared: 'Cache limpa',
    about: 'Acerca',
    aboutText: 'Aeris oferece previsões do tempo com um design moderno, elegante e fácil de usar. Os dados meteorológicos são fornecidos pela Open‑Meteo, garantindo informações confiáveis e atualizadas para o seu dia a dia.',
    humidity: 'Humidade', pressure: 'Pressão', wind: 'Vento', gusts: 'Rajadas', visibility: 'Visibilidade',
    uvIndex: 'Índice UV', sunrise: 'Nascer do sol', sunset: 'Pôr do sol', dewPoint: 'Ponto de orvalho',
    airQuality: 'Qualidade do ar', moonPhase: 'Fase da lua', rainChance: 'Prob. de chuva',
    uvLow: 'Baixo', uvModerate: 'Moderado', uvHigh: 'Alto', uvVeryHigh: 'Muito alto', uvExtreme: 'Extremo',
    aqiGood: 'Boa', aqiFair: 'Razoável', aqiModerate: 'Moderada', aqiPoor: 'Fraca', aqiVeryPoor: 'Muito fraca', aqiHazardous: 'Perigosa',
    alertCyclone: 'Alerta de ciclone', alertSevereWind: 'Vento extremo', alertStrongWind: 'Vento forte',
    alertStorm: 'Trovoada forte a caminho', alertHeavyRain: 'Chuva intensa prevista',
    alertGustsUpTo: 'Rajadas até {n} km/h previstas nos próximos dias', alertDismiss: 'Dispensar',
    mistLabel: 'Neblina', alertFog: 'Nevoeiro reduz a visibilidade', alertFromTime: 'A partir de {day} às {time}',
    tipUmbrella: 'Leve um guarda-chuva hoje', tipSunscreen: 'UV elevado — use protetor solar',
    tipWindy: 'Dia ventoso, cuidado ao ar livre', tipCold: 'Está frio — vista-se bem', tipPleasant: 'Dia agradável para sair',
    home: 'Início', search: 'Pesquisar', favorites: 'Favoritos', settings: 'Ajustes',
    addedFav: 'Adicionada aos favoritos', removedFav: 'Removida dos favoritos',
    shareLabel: 'Partilhar', shareGenerating: 'A preparar imagem…', shareError: 'Não foi possível gerar a imagem',
    locateError: 'Não foi possível obter a sua localização.',
    shareSheetTitle: 'Partilhar clima', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X (Twitter)', shareTelegram: 'Telegram', shareEmail: 'Email',
    shareCopyLink: 'Copiar texto', shareCopied: 'Copiado!', shareDownloadImg: 'Guardar imagem', shareMoreApps: 'Mais aplicações', locateSettingsLabel: 'Usar localização atual', locating: 'A localizar…',
    loadError: 'Sem ligação. A mostrar os últimos dados disponíveis.',
    noResults: 'Nenhuma cidade encontrada.', currentLocation: 'Localização atual',
    today: 'Hoje', tomorrow: 'Amanhã',
    weekdays: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
    weekdaysShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'],
    months: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],

    // --- Alerta hiperlocal de chuva ---
    rainNow: 'A chover agora',
    rainIn: 'Chuva em {n} min',
    rainNone: 'Sem chuva prevista nas próximas {h}h',
    rainAlertTitle: 'Chuva a caminho',

    // --- Dicas contextuais (dailyTip expandido) ---
    tipRainingNow: 'Está a chover — leve guarda-chuva',
    tipRainSoon: 'Chuva em {n} min — proteja-se',
    tipRainAt: 'Leve capa, chuva prevista às {time}',
    tipUmbrellaGeneric: 'Leve um guarda-chuva hoje',
    tipSunscreen: 'UV elevado — use protetor solar',
    tipWindy: 'Dia ventoso, cuidado ao ar livre',
    tipCold: 'Está frio — vista-se bem',
    tipLaundry: 'Céu limpo e seco — boa hora para lavar roupa',
    tipPleasantGeneric: 'Dia agradável para sair',

    // --- Comparação histórica ---
    historicalTitle: 'Comparação histórica',
    historicalAbove: '{diff}° acima da média para esta época em {city}',
    historicalBelow: '{diff}° abaixo da média para esta época em {city}',
    historicalNormal: 'Perto da média histórica para esta época em {city}',
    historicalAvgLabel: 'Média histórica de hoje: {avg}°',

    // --- Modo offline reforçado ---
    offlineBadge: 'Offline',
    offlineDataFrom: 'Sem ligação · a mostrar dados de há {n} min',
    offlineDataFromNow: 'Sem ligação · a mostrar os últimos dados guardados',
  },
  en: {
    loading: 'Loading…', splashSub: 'preparing your sky…',
    searchPlaceholder: 'Search city…',
    feelsLike: 'Feels like',
    next24h: 'Next 24 hours', next7d: '7-day forecast', details: 'Details',
    tempChart: 'Temperature chart',
    dataSource: 'Data provided by Open‑Meteo',
    updatedNow: 'Updated just now · tap to refresh',
    updatedAgo: 'Updated {n} min ago · tap to refresh',
    updating: 'Refreshing…', refreshed: 'Data refreshed', refreshFailed: 'Could not refresh right now',
    searchTitle: 'Search', searchSub: 'Find the weather for any city in the world',
    recentSearches: 'Recent searches',
    noRecents: 'No recent searches yet.',
    nowLabel: 'Now',
    noData: 'No data',
    favoritesTitle: 'Favorites', favoritesSub: 'Your saved cities',
    favEmpty: 'No favorite cities yet.',
    favEmptyHint: 'Tap the star on the home screen to save a city.',
    settingsTitle: 'Settings', settingsSub: 'Personalize your experience',
    tempUnit: 'Temperature unit', language: 'Language', selectLanguage: 'Select language',
    theme: 'Theme', themeAuto: 'Auto', themeLight: 'Light', themeDark: 'Dark',
    allowLocation: 'Allow location', autoRefresh: 'Auto refresh',
    moreFeatures: 'More features',
    lowDataMode: 'Low data mode', dailyTipsLabel: 'Daily tips',
    clearCache: 'Clear cache', cacheCleared: 'Cache cleared',
    about: 'About',
    aboutText: 'A premium weather app, built with real glassmorphism and attention to detail. Data provided by Open‑Meteo.',
    humidity: 'Humidity', pressure: 'Pressure', wind: 'Wind', gusts: 'Gusts', visibility: 'Visibility',
    uvIndex: 'UV Index', sunrise: 'Sunrise', sunset: 'Sunset', dewPoint: 'Dew point',
    airQuality: 'Air quality', moonPhase: 'Moon phase', rainChance: 'Rain chance',
    uvLow: 'Low', uvModerate: 'Moderate', uvHigh: 'High', uvVeryHigh: 'Very high', uvExtreme: 'Extreme',
    aqiGood: 'Good', aqiFair: 'Fair', aqiModerate: 'Moderate', aqiPoor: 'Poor', aqiVeryPoor: 'Very poor', aqiHazardous: 'Hazardous',
    alertCyclone: 'Cyclone alert', alertSevereWind: 'Extreme wind', alertStrongWind: 'Strong wind',
    alertStorm: 'Severe thunderstorm approaching', alertHeavyRain: 'Heavy rain expected',
    alertGustsUpTo: 'Gusts up to {n} km/h expected in the coming days', alertDismiss: 'Dismiss',
    mistLabel: 'Mist', alertFog: 'Fog reducing visibility', alertFromTime: 'Starting {day} at {time}',
    tipUmbrella: 'Bring an umbrella today', tipSunscreen: 'High UV — wear sunscreen',
    tipWindy: 'Windy day, be careful outdoors', tipCold: "It's cold — dress warmly", tipPleasant: 'Pleasant day to go outside',
    home: 'Home', search: 'Search', favorites: 'Favorites', settings: 'Settings',
    addedFav: 'Added to favorites', removedFav: 'Removed from favorites',
    shareLabel: 'Share', shareGenerating: 'Preparing image…', shareError: 'Could not generate the image',
    locateError: 'Could not get your location.',
    shareSheetTitle: 'Share weather', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X (Twitter)', shareTelegram: 'Telegram', shareEmail: 'Email',
    shareCopyLink: 'Copy text', shareCopied: 'Copied!', shareDownloadImg: 'Save image', shareMoreApps: 'More apps', locateSettingsLabel: 'Use current location', locating: 'Locating…',
    loadError: 'No connection. Showing the last available data.',
    noResults: 'No cities found.', currentLocation: 'Current location',
    today: 'Today', tomorrow: 'Tomorrow',
    weekdays: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
    weekdaysShort: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],

    rainNow: 'Raining now',
    rainIn: 'Rain in {n} min',
    rainNone: 'No rain expected in the next {h}h',
    rainAlertTitle: 'Rain on the way',

    tipRainingNow: "It's raining — bring an umbrella",
    tipRainSoon: 'Rain in {n} min — take cover',
    tipRainAt: 'Bring a raincoat, rain expected at {time}',
    tipUmbrellaGeneric: 'Bring an umbrella today',
    tipSunscreen: 'High UV — wear sunscreen',
    tipWindy: 'Windy day, be careful outdoors',
    tipCold: "It's cold — dress warmly",
    tipLaundry: 'Clear and dry — good time to do laundry',
    tipPleasantGeneric: 'Pleasant day to go out',

    historicalTitle: 'Historical comparison',
    historicalAbove: '{diff}° above average for this time of year in {city}',
    historicalBelow: '{diff}° below average for this time of year in {city}',
    historicalNormal: 'Close to the historical average for this time of year in {city}',
    historicalAvgLabel: "Today's historical average: {avg}°",

    offlineBadge: 'Offline',
    offlineDataFrom: 'No connection · showing data from {n} min ago',
    offlineDataFromNow: 'No connection · showing the last saved data',
  },
  es: {
    loading: 'Cargando…', splashSub: 'preparando tu cielo…',
    searchPlaceholder: 'Buscar ciudad…',
    feelsLike: 'Sensación térmica de',
    next24h: 'Próximas 24 horas', next7d: 'Previsión a 7 días', details: 'Detalles',
    tempChart: 'Gráfico de temperatura',
    dataSource: 'Datos proporcionados por Open‑Meteo',
    updatedNow: 'Actualizado ahora · toca para actualizar',
    updatedAgo: 'Actualizado hace {n} min · toca para actualizar',
    updating: 'Actualizando…', refreshed: 'Datos actualizados', refreshFailed: 'No se pudo actualizar ahora',
    searchTitle: 'Buscar', searchSub: 'Encuentra el clima de cualquier ciudad del mundo',
    recentSearches: 'Búsquedas recientes',
    noRecents: 'Aún no hay búsquedas recientes.',
    nowLabel: 'Ahora',
    noData: 'Sin datos',
    favoritesTitle: 'Favoritos', favoritesSub: 'Tus ciudades guardadas',
    favEmpty: 'Aún no tienes ciudades favoritas.',
    favEmptyHint: 'Toca la estrella en la pantalla principal para guardar una ciudad.',
    settingsTitle: 'Ajustes', settingsSub: 'Personaliza tu experiencia',
    tempUnit: 'Unidad de temperatura', language: 'Idioma', selectLanguage: 'Seleccionar idioma',
    theme: 'Tema', themeAuto: 'Auto', themeLight: 'Claro', themeDark: 'Oscuro',
    allowLocation: 'Permitir ubicación', autoRefresh: 'Actualización automática',
    moreFeatures: 'Más funciones',
    lowDataMode: 'Modo ahorro de datos', dailyTipsLabel: 'Sugerencias diarias',
    clearCache: 'Borrar caché', cacheCleared: 'Caché borrada',
    about: 'Acerca de',
    aboutText: 'Una app de clima premium, hecha con vidrio esmerilado real y atención al detalle. Datos de Open‑Meteo.',
    humidity: 'Humedad', pressure: 'Presión', wind: 'Viento', gusts: 'Ráfagas', visibility: 'Visibilidad',
    uvIndex: 'Índice UV', sunrise: 'Amanecer', sunset: 'Atardecer', dewPoint: 'Punto de rocío',
    airQuality: 'Calidad del aire', moonPhase: 'Fase lunar', rainChance: 'Prob. de lluvia',
    uvLow: 'Bajo', uvModerate: 'Moderado', uvHigh: 'Alto', uvVeryHigh: 'Muy alto', uvExtreme: 'Extremo',
    aqiGood: 'Buena', aqiFair: 'Aceptable', aqiModerate: 'Moderada', aqiPoor: 'Mala', aqiVeryPoor: 'Muy mala', aqiHazardous: 'Peligrosa',
    alertCyclone: 'Alerta de ciclón', alertSevereWind: 'Viento extremo', alertStrongWind: 'Viento fuerte',
    alertStorm: 'Tormenta fuerte en camino', alertHeavyRain: 'Se prevé lluvia intensa',
    alertGustsUpTo: 'Ráfagas de hasta {n} km/h previstas en los próximos días', alertDismiss: 'Descartar',
    mistLabel: 'Neblina', alertFog: 'Niebla reduce la visibilidad', alertFromTime: 'A partir de {day} a las {time}',
    tipUmbrella: 'Lleva un paraguas hoy', tipSunscreen: 'UV alto — usa protector solar',
    tipWindy: 'Día ventoso, ten cuidado al aire libre', tipCold: 'Hace frío — abrígate bien', tipPleasant: 'Buen día para salir',
    home: 'Inicio', search: 'Buscar', favorites: 'Favoritos', settings: 'Ajustes',
    addedFav: 'Añadida a favoritos', removedFav: 'Eliminada de favoritos',
    shareLabel: 'Compartir', shareGenerating: 'Preparando imagen…', shareError: 'No se pudo generar la imagen',
    locateError: 'No se pudo obtener tu ubicación.',
    shareSheetTitle: 'Compartir clima', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X (Twitter)', shareTelegram: 'Telegram', shareEmail: 'Correo',
    shareCopyLink: 'Copiar texto', shareCopied: '¡Copiado!', shareDownloadImg: 'Guardar imagen', shareMoreApps: 'Más aplicaciones', locateSettingsLabel: 'Usar ubicación actual', locating: 'Localizando…',
    loadError: 'Sin conexión. Mostrando los últimos datos disponibles.',
    noResults: 'No se encontraron ciudades.', currentLocation: 'Ubicación actual',
    today: 'Hoy', tomorrow: 'Mañana',
    weekdays: ['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],
    weekdaysShort: ['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
    months: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
  },
  fr: {
    loading: 'Chargement…', splashSub: 'préparation de votre ciel…',
    searchPlaceholder: 'Rechercher une ville…',
    feelsLike: 'Ressenti de',
    next24h: 'Prochaines 24 heures', next7d: 'Prévisions sur 7 jours', details: 'Détails',
    tempChart: 'Graphique de température',
    dataSource: 'Données fournies par Open‑Meteo',
    updatedNow: "Mis à jour à l'instant · touchez pour actualiser",
    updatedAgo: 'Mis à jour il y a {n} min · touchez pour actualiser',
    updating: 'Actualisation…', refreshed: 'Données actualisées', refreshFailed: "Impossible d'actualiser pour le moment",
    searchTitle: 'Rechercher', searchSub: "Trouvez la météo de n'importe quelle ville",
    recentSearches: 'Recherches récentes',
    noRecents: 'Aucune recherche récente pour le moment.',
    nowLabel: 'Maintenant',
    noData: 'Aucune donnée',
    favoritesTitle: 'Favoris', favoritesSub: 'Vos villes enregistrées',
    favEmpty: 'Aucune ville favorite pour le moment.',
    favEmptyHint: "Touchez l'étoile sur l'écran d'accueil pour enregistrer une ville.",
    settingsTitle: 'Réglages', settingsSub: 'Personnalisez votre expérience',
    tempUnit: 'Unité de température', language: 'Langue', selectLanguage: 'Choisir la langue',
    theme: 'Thème', themeAuto: 'Auto', themeLight: 'Clair', themeDark: 'Sombre',
    allowLocation: 'Autoriser la localisation', autoRefresh: 'Actualisation automatique',
    moreFeatures: 'Plus de fonctionnalités',
    lowDataMode: 'Mode économie de données', dailyTipsLabel: 'Conseils du jour',
    clearCache: 'Vider le cache', cacheCleared: 'Cache vidé',
    about: 'À propos',
    aboutText: 'Une app météo premium, avec un vrai effet de verre dépoli et un grand soin du détail. Données Open‑Meteo.',
    humidity: 'Humidité', pressure: 'Pression', wind: 'Vent', gusts: 'Rafales', visibility: 'Visibilité',
    uvIndex: 'Indice UV', sunrise: 'Lever du soleil', sunset: 'Coucher du soleil', dewPoint: 'Point de rosée',
    airQuality: "Qualité de l'air", moonPhase: 'Phase lunaire', rainChance: 'Prob. de pluie',
    uvLow: 'Faible', uvModerate: 'Modéré', uvHigh: 'Élevé', uvVeryHigh: 'Très élevé', uvExtreme: 'Extrême',
    aqiGood: 'Bonne', aqiFair: 'Correcte', aqiModerate: 'Modérée', aqiPoor: 'Mauvaise', aqiVeryPoor: 'Très mauvaise', aqiHazardous: 'Dangereuse',
    alertCyclone: 'Alerte cyclone', alertSevereWind: 'Vent extrême', alertStrongWind: 'Vent fort',
    alertStorm: 'Orage violent en approche', alertHeavyRain: 'Fortes pluies prévues',
    alertGustsUpTo: 'Rafales jusqu\'à {n} km/h prévues dans les prochains jours', alertDismiss: 'Ignorer',
    shareSheetTitle: 'Partager la météo', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X (Twitter)', shareTelegram: 'Telegram', shareEmail: 'E-mail',
    shareCopyLink: 'Copier le texte', shareCopied: 'Copié !', shareDownloadImg: 'Enregistrer l\'image', shareMoreApps: 'Plus d\'applications', locateSettingsLabel: 'Utiliser la position actuelle', locating: 'Localisation…',
    mistLabel: 'Brume', alertFog: 'Le brouillard réduit la visibilité', alertFromTime: 'À partir de {day} à {time}',
    tipUmbrella: 'Prenez un parapluie aujourd\'hui', tipSunscreen: 'UV élevé — utilisez une crème solaire',
    tipWindy: 'Journée venteuse, soyez prudent dehors', tipCold: 'Il fait froid — habillez-vous chaudement', tipPleasant: 'Belle journée pour sortir',
    home: 'Accueil', search: 'Rechercher', favorites: 'Favoris', settings: 'Réglages',
    addedFav: 'Ajouté aux favoris', removedFav: 'Retiré des favoris',
    shareLabel: 'Partager', shareGenerating: "Préparation de l'image…", shareError: "Impossible de générer l'image",
    locateError: "Impossible d'obtenir votre position.",
    loadError: 'Pas de connexion. Affichage des dernières données disponibles.',
    noResults: 'Aucune ville trouvée.', currentLocation: 'Position actuelle',
    today: "Aujourd'hui", tomorrow: 'Demain',
    weekdays: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
    weekdaysShort: ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
    months: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
  },
  de: {
    loading: 'Wird geladen…', splashSub: 'Ihr Himmel wird vorbereitet…',
    searchPlaceholder: 'Stadt suchen…',
    feelsLike: 'Gefühlt wie',
    next24h: 'Nächste 24 Stunden', next7d: '7-Tage-Vorhersage', details: 'Details',
    tempChart: 'Temperaturverlauf',
    dataSource: 'Daten bereitgestellt von Open‑Meteo',
    updatedNow: 'Gerade aktualisiert · zum Aktualisieren tippen',
    updatedAgo: 'Vor {n} Min. aktualisiert · zum Aktualisieren tippen',
    updating: 'Wird aktualisiert…', refreshed: 'Daten aktualisiert', refreshFailed: 'Aktualisierung derzeit nicht möglich',
    searchTitle: 'Suchen', searchSub: 'Finden Sie das Wetter für jede Stadt der Welt',
    recentSearches: 'Letzte Suchen',
    noRecents: 'Noch keine letzten Suchen.',
    nowLabel: 'Jetzt',
    noData: 'Keine Daten',
    favoritesTitle: 'Favoriten', favoritesSub: 'Ihre gespeicherten Städte',
    favEmpty: 'Noch keine Favoriten.',
    favEmptyHint: 'Tippen Sie auf den Stern auf dem Startbildschirm, um eine Stadt zu speichern.',
    settingsTitle: 'Einstellungen', settingsSub: 'Passen Sie Ihre Erfahrung an',
    tempUnit: 'Temperatureinheit', language: 'Sprache', selectLanguage: 'Sprache auswählen',
    theme: 'Design', themeAuto: 'Auto', themeLight: 'Hell', themeDark: 'Dunkel',
    allowLocation: 'Standort erlauben', autoRefresh: 'Automatische Aktualisierung',
    moreFeatures: 'Weitere Funktionen',
    lowDataMode: 'Datensparmodus', dailyTipsLabel: 'Tägliche Tipps',
    clearCache: 'Cache leeren', cacheCleared: 'Cache geleert',
    about: 'Über',
    aboutText: 'Eine Premium-Wetter-App mit echtem Glaseffekt und viel Liebe zum Detail. Daten von Open‑Meteo.',
    humidity: 'Luftfeuchtigkeit', pressure: 'Luftdruck', wind: 'Wind', gusts: 'Böen', visibility: 'Sichtweite',
    uvIndex: 'UV-Index', sunrise: 'Sonnenaufgang', sunset: 'Sonnenuntergang', dewPoint: 'Taupunkt',
    airQuality: 'Luftqualität', moonPhase: 'Mondphase', rainChance: 'Regenwahrsch.',
    uvLow: 'Niedrig', uvModerate: 'Mäßig', uvHigh: 'Hoch', uvVeryHigh: 'Sehr hoch', uvExtreme: 'Extrem',
    aqiGood: 'Gut', aqiFair: 'Mäßig', aqiModerate: 'Mittel', aqiPoor: 'Schlecht', aqiVeryPoor: 'Sehr schlecht', aqiHazardous: 'Gefährlich',
    alertCyclone: 'Zyklonwarnung', alertSevereWind: 'Extremer Wind', alertStrongWind: 'Starker Wind',
    alertStorm: 'Schweres Gewitter im Anzug', alertHeavyRain: 'Starker Regen erwartet',
    alertGustsUpTo: 'Böen bis zu {n} km/h in den nächsten Tagen erwartet', alertDismiss: 'Verwerfen',
    mistLabel: 'Dunst', alertFog: 'Nebel schränkt die Sicht ein', alertFromTime: '{day} ab {time} Uhr',
    tipUmbrella: 'Nehmen Sie heute einen Regenschirm mit', tipSunscreen: 'Hoher UV-Wert — Sonnencreme verwenden',
    tipWindy: 'Windiger Tag, im Freien vorsichtig sein', tipCold: 'Es ist kalt — warm anziehen', tipPleasant: 'Angenehmer Tag zum Rausgehen',
    home: 'Start', search: 'Suche', favorites: 'Favoriten', settings: 'Einstellungen',
    addedFav: 'Zu Favoriten hinzugefügt', removedFav: 'Aus Favoriten entfernt',
    shareLabel: 'Teilen', shareGenerating: 'Bild wird vorbereitet…', shareError: 'Bild konnte nicht erstellt werden',
    locateError: 'Standort konnte nicht ermittelt werden.',
    shareSheetTitle: 'Wetter teilen', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X (Twitter)', shareTelegram: 'Telegram', shareEmail: 'E-Mail',
    shareCopyLink: 'Text kopieren', shareCopied: 'Kopiert!', shareDownloadImg: 'Bild speichern', shareMoreApps: 'Weitere Apps', locateSettingsLabel: 'Aktuellen Standort verwenden', locating: 'Standort wird ermittelt…',
    loadError: 'Keine Verbindung. Letzte verfügbare Daten werden angezeigt.',
    noResults: 'Keine Städte gefunden.', currentLocation: 'Aktueller Standort',
    today: 'Heute', tomorrow: 'Morgen',
    weekdays: ['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],
    weekdaysShort: ['So','Mo','Di','Mi','Do','Fr','Sa'],
    months: ['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
  },
  it: {
    loading: 'Caricamento…', splashSub: 'preparando il tuo cielo…',
    searchPlaceholder: 'Cerca città…',
    feelsLike: 'Percepita di',
    next24h: 'Prossime 24 ore', next7d: 'Previsioni a 7 giorni', details: 'Dettagli',
    tempChart: 'Grafico della temperatura',
    dataSource: 'Dati forniti da Open‑Meteo',
    updatedNow: 'Aggiornato ora · tocca per aggiornare',
    updatedAgo: 'Aggiornato {n} min fa · tocca per aggiornare',
    updating: 'Aggiornamento…', refreshed: 'Dati aggiornati', refreshFailed: 'Impossibile aggiornare ora',
    searchTitle: 'Cerca', searchSub: 'Trova il meteo di qualsiasi città del mondo',
    recentSearches: 'Ricerche recenti',
    noRecents: 'Ancora nessuna ricerca recente.',
    nowLabel: 'Ora',
    noData: 'Nessun dato',
    favoritesTitle: 'Preferiti', favoritesSub: 'Le tue città salvate',
    favEmpty: 'Nessuna città preferita ancora.',
    favEmptyHint: 'Tocca la stella nella schermata principale per salvare una città.',
    settingsTitle: 'Impostazioni', settingsSub: 'Personalizza la tua esperienza',
    tempUnit: 'Unità di temperatura', language: 'Lingua', selectLanguage: 'Seleziona lingua',
    theme: 'Tema', themeAuto: 'Auto', themeLight: 'Chiaro', themeDark: 'Scuro',
    allowLocation: 'Consenti posizione', autoRefresh: 'Aggiornamento automatico',
    moreFeatures: 'Altre funzionalità',
    lowDataMode: 'Modalità risparmio dati', dailyTipsLabel: 'Suggerimenti giornalieri',
    clearCache: 'Svuota cache', cacheCleared: 'Cache svuotata',
    about: 'Info',
    aboutText: "Un'app meteo premium, con vero effetto vetro smerigliato e cura per i dettagli. Dati forniti da Open‑Meteo.",
    humidity: 'Umidità', pressure: 'Pressione', wind: 'Vento', gusts: 'Raffiche', visibility: 'Visibilità',
    uvIndex: 'Indice UV', sunrise: 'Alba', sunset: 'Tramonto', dewPoint: 'Punto di rugiada',
    airQuality: "Qualità dell'aria", moonPhase: 'Fase lunare', rainChance: 'Prob. di pioggia',
    uvLow: 'Basso', uvModerate: 'Moderato', uvHigh: 'Alto', uvVeryHigh: 'Molto alto', uvExtreme: 'Estremo',
    aqiGood: 'Buona', aqiFair: 'Discreta', aqiModerate: 'Moderata', aqiPoor: 'Scarsa', aqiVeryPoor: 'Molto scarsa', aqiHazardous: 'Pericolosa',
    alertCyclone: 'Allerta ciclone', alertSevereWind: 'Vento estremo', alertStrongWind: 'Vento forte',
    alertStorm: 'Forte temporale in arrivo', alertHeavyRain: 'Pioggia intensa prevista',
    alertGustsUpTo: 'Raffiche fino a {n} km/h previste nei prossimi giorni', alertDismiss: 'Ignora',
    mistLabel: 'Foschia', alertFog: 'La nebbia riduce la visibilità', alertFromTime: 'A partire da {day} alle {time}',
    tipUmbrella: 'Porta un ombrello oggi', tipSunscreen: 'UV elevato — usa la protezione solare',
    tipWindy: "Giornata ventosa, attenzione all'aperto", tipCold: 'Fa freddo — vestiti bene', tipPleasant: 'Bella giornata per uscire',
    home: 'Home', search: 'Cerca', favorites: 'Preferiti', settings: 'Impostazioni',
    addedFav: 'Aggiunta ai preferiti', removedFav: 'Rimossa dai preferiti',
    shareLabel: 'Condividi', shareGenerating: "Preparazione immagine…", shareError: "Impossibile generare l'immagine",
    locateError: 'Impossibile ottenere la tua posizione.',
    shareSheetTitle: 'Condividi meteo', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X (Twitter)', shareTelegram: 'Telegram', shareEmail: 'Email',
    shareCopyLink: 'Copia testo', shareCopied: 'Copiato!', shareDownloadImg: 'Salva immagine', shareMoreApps: 'Altre app', locateSettingsLabel: 'Usa posizione attuale', locating: 'Localizzazione…',
    loadError: 'Nessuna connessione. Vengono mostrati gli ultimi dati disponibili.',
    noResults: 'Nessuna città trovata.', currentLocation: 'Posizione attuale',
    today: 'Oggi', tomorrow: 'Domani',
    weekdays: ['Domenica','Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato'],
    weekdaysShort: ['Dom','Lun','Mar','Mer','Gio','Ven','Sab'],
    months: ['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'],
  },
  zh: {
    loading: '加载中…', splashSub: '正在准备您的天空…',
    searchPlaceholder: '搜索城市…',
    feelsLike: '体感温度',
    next24h: '未来24小时', next7d: '7天预报', details: '详情',
    tempChart: '温度图表',
    dataSource: '数据由 Open‑Meteo 提供',
    updatedNow: '刚刚更新 · 点击刷新',
    updatedAgo: '{n} 分钟前更新 · 点击刷新',
    updating: '正在刷新…', refreshed: '数据已更新', refreshFailed: '暂时无法刷新',
    searchTitle: '搜索', searchSub: '查找世界任何城市的天气',
    recentSearches: '最近搜索',
    noRecents: '暂无最近搜索。',
    nowLabel: '现在',
    noData: '无数据',
    favoritesTitle: '收藏', favoritesSub: '您保存的城市',
    favEmpty: '还没有收藏的城市。',
    favEmptyHint: '在主屏幕上点击星标以保存城市。',
    settingsTitle: '设置', settingsSub: '个性化您的体验',
    tempUnit: '温度单位', language: '语言', selectLanguage: '选择语言',
    theme: '主题', themeAuto: '自动', themeLight: '浅色', themeDark: '深色',
    allowLocation: '允许定位', autoRefresh: '自动刷新',
    moreFeatures: '更多功能',
    lowDataMode: '省流量模式', dailyTipsLabel: '每日建议',
    clearCache: '清除缓存', cacheCleared: '缓存已清除',
    about: '关于',
    aboutText: '一款高级天气应用，采用真实的毛玻璃效果，注重细节。数据由 Open‑Meteo 提供。',
    humidity: '湿度', pressure: '气压', wind: '风速', gusts: '阵风', visibility: '能见度',
    uvIndex: '紫外线指数', sunrise: '日出', sunset: '日落', dewPoint: '露点',
    airQuality: '空气质量', moonPhase: '月相', rainChance: '降雨概率',
    uvLow: '低', uvModerate: '中等', uvHigh: '高', uvVeryHigh: '很高', uvExtreme: '极高',
    aqiGood: '良好', aqiFair: '一般', aqiModerate: '中等', aqiPoor: '较差', aqiVeryPoor: '很差', aqiHazardous: '危险',
    alertCyclone: '气旋警报', alertSevereWind: '极端大风', alertStrongWind: '大风',
    alertStorm: '强雷暴即将来袭', alertHeavyRain: '预计有强降雨',
    alertGustsUpTo: '未来几天预计阵风达 {n} 公里/小时', alertDismiss: '关闭',
    mistLabel: '轻雾', alertFog: '雾导致能见度降低', alertFromTime: '{day} {time} 开始',
    tipUmbrella: '今天请带雨伞', tipSunscreen: '紫外线较强 — 请涂防晒霜',
    tipWindy: '大风天气，户外活动请注意', tipCold: '天气寒冷 — 请注意保暖', tipPleasant: '适宜外出的好天气',
    home: '首页', search: '搜索', favorites: '收藏', settings: '设置',
    addedFav: '已加入收藏', removedFav: '已移除收藏',
    shareLabel: '分享', shareGenerating: '正在生成图片…', shareError: '无法生成图片',
    locateError: '无法获取您的位置。',
    shareSheetTitle: '分享天气', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X（Twitter）', shareTelegram: 'Telegram', shareEmail: '邮件',
    shareCopyLink: '复制文字', shareCopied: '已复制！', shareDownloadImg: '保存图片', shareMoreApps: '更多应用', locateSettingsLabel: '使用当前位置', locating: '正在定位…',
    loadError: '无网络连接，正在显示最近可用的数据。',
    noResults: '未找到城市。', currentLocation: '当前位置',
    today: '今天', tomorrow: '明天',
    weekdays: ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],
    weekdaysShort: ['周日','周一','周二','周三','周四','周五','周六'],
    months: ['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'],
  },
  ar: {
    loading: 'جارٍ التحميل…', splashSub: 'جارٍ تجهيز سمائك…',
    searchPlaceholder: 'ابحث عن مدينة…',
    feelsLike: 'الإحساس الحراري',
    next24h: 'الساعات الـ 24 القادمة', next7d: 'توقعات 7 أيام', details: 'التفاصيل',
    tempChart: 'مخطط درجة الحرارة',
    dataSource: 'البيانات مقدَّمة من Open‑Meteo',
    updatedNow: 'تم التحديث الآن · اضغط للتحديث',
    updatedAgo: 'تم التحديث قبل {n} دقيقة · اضغط للتحديث',
    updating: 'جارٍ التحديث…', refreshed: 'تم تحديث البيانات', refreshFailed: 'تعذّر التحديث الآن',
    searchTitle: 'بحث', searchSub: 'اعثر على حالة الطقس لأي مدينة في العالم',
    recentSearches: 'عمليات بحث حديثة',
    noRecents: 'لا توجد عمليات بحث حديثة بعد.',
    nowLabel: 'الآن',
    noData: 'لا توجد بيانات',
    favoritesTitle: 'المفضلة', favoritesSub: 'المدن المحفوظة لديك',
    favEmpty: 'لا توجد مدن مفضلة بعد.',
    favEmptyHint: 'اضغط على النجمة في الشاشة الرئيسية لحفظ مدينة.',
    settingsTitle: 'الإعدادات', settingsSub: 'خصّص تجربتك',
    tempUnit: 'وحدة درجة الحرارة', language: 'اللغة', selectLanguage: 'اختر اللغة',
    theme: 'المظهر', themeAuto: 'تلقائي', themeLight: 'فاتح', themeDark: 'داكن',
    allowLocation: 'السماح بالموقع', autoRefresh: 'تحديث تلقائي',
    moreFeatures: 'ميزات إضافية',
    lowDataMode: 'وضع توفير البيانات', dailyTipsLabel: 'نصائح يومية',
    clearCache: 'مسح ذاكرة التخزين المؤقت', cacheCleared: 'تم مسح الذاكرة المؤقتة',
    about: 'حول التطبيق',
    aboutText: 'تطبيق طقس متميز، بتأثير زجاج ضبابي حقيقي واهتمام بالتفاصيل. البيانات من Open‑Meteo.',
    humidity: 'الرطوبة', pressure: 'الضغط الجوي', wind: 'الرياح', gusts: 'هبّات الرياح', visibility: 'مدى الرؤية',
    uvIndex: 'مؤشر الأشعة فوق البنفسجية', sunrise: 'شروق الشمس', sunset: 'غروب الشمس', dewPoint: 'نقطة الندى',
    airQuality: 'جودة الهواء', moonPhase: 'طور القمر', rainChance: 'احتمال المطر',
    uvLow: 'منخفض', uvModerate: 'متوسط', uvHigh: 'مرتفع', uvVeryHigh: 'مرتفع جدًا', uvExtreme: 'شديد',
    aqiGood: 'جيدة', aqiFair: 'مقبولة', aqiModerate: 'متوسطة', aqiPoor: 'ضعيفة', aqiVeryPoor: 'ضعيفة جدًا', aqiHazardous: 'خطيرة',
    alertCyclone: 'تنبيه إعصار', alertSevereWind: 'رياح شديدة القوة', alertStrongWind: 'رياح قوية',
    alertStorm: 'عاصفة رعدية قوية قادمة', alertHeavyRain: 'أمطار غزيرة متوقعة',
    alertGustsUpTo: 'هبّات رياح تصل إلى {n} كم/س متوقعة خلال الأيام القادمة', alertDismiss: 'إغلاق',
    mistLabel: 'ضباب خفيف', alertFog: 'الضباب يقلل من مدى الرؤية', alertFromTime: 'ابتداءً من {day} الساعة {time}',
    tipUmbrella: 'أحضر مظلة اليوم', tipSunscreen: 'أشعة فوق بنفسجية مرتفعة — استخدم واقي الشمس',
    tipWindy: 'يوم عاصف، كن حذرًا في الخارج', tipCold: 'الجو بارد — البس ملابس دافئة', tipPleasant: 'يوم لطيف للخروج',
    home: 'الرئيسية', search: 'بحث', favorites: 'المفضلة', settings: 'الإعدادات',
    addedFav: 'أُضيفت إلى المفضلة', removedFav: 'أُزيلت من المفضلة',
    shareLabel: 'مشاركة', shareGenerating: 'جارٍ إعداد الصورة…', shareError: 'تعذّر إنشاء الصورة',
    locateError: 'تعذّر تحديد موقعك.',
    shareSheetTitle: 'مشاركة الطقس', shareWhatsapp: 'واتساب', shareFacebook: 'فيسبوك', shareTwitter: 'X (تويتر)', shareTelegram: 'تيليجرام', shareEmail: 'البريد الإلكتروني',
    shareCopyLink: 'نسخ النص', shareCopied: 'تم النسخ!', shareDownloadImg: 'حفظ الصورة', shareMoreApps: 'تطبيقات أخرى', locateSettingsLabel: 'استخدام الموقع الحالي', locating: 'جارٍ تحديد الموقع…',
    loadError: 'لا يوجد اتصال. يتم عرض آخر بيانات متاحة.',
    noResults: 'لم يتم العثور على مدن.', currentLocation: 'الموقع الحالي',
    today: 'اليوم', tomorrow: 'غدًا',
    weekdays: ['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'],
    weekdaysShort: ['أحد','إثن','ثلا','أرب','خمي','جمع','سبت'],
    months: ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
  },
  sw: {
    loading: 'Inapakia…', splashSub: 'inaandaa anga lako…',
    searchPlaceholder: 'Tafuta mji…',
    feelsLike: 'Hali inayohisiwa',
    next24h: 'Masaa 24 yajayo', next7d: 'Utabiri wa siku 7', details: 'Maelezo',
    tempChart: 'Chati ya joto',
    dataSource: 'Data imetolewa na Open‑Meteo',
    updatedNow: 'Imesasishwa sasa hivi · gusa kusasisha',
    updatedAgo: 'Imesasishwa dakika {n} zilizopita · gusa kusasisha',
    updating: 'Inasasisha…', refreshed: 'Data imesasishwa', refreshFailed: 'Imeshindwa kusasisha sasa',
    searchTitle: 'Tafuta', searchSub: 'Pata hali ya hewa ya mji wowote duniani',
    recentSearches: 'Utafutaji wa hivi karibuni',
    noRecents: 'Bado hakuna utafutaji wa hivi karibuni.',
    nowLabel: 'Sasa',
    noData: 'Hakuna data',
    favoritesTitle: 'Vipendwa', favoritesSub: 'Miji uliyohifadhi',
    favEmpty: 'Bado hakuna miji uliyopenda.',
    favEmptyHint: 'Gusa nyota kwenye skrini kuu ili kuhifadhi mji.',
    settingsTitle: 'Mipangilio', settingsSub: 'Binafsisha matumizi yako',
    tempUnit: 'Kipimo cha joto', language: 'Lugha', selectLanguage: 'Chagua lugha',
    theme: 'Mandhari', themeAuto: 'Kiotomatiki', themeLight: 'Nyepesi', themeDark: 'Giza',
    allowLocation: 'Ruhusu mahali', autoRefresh: 'Kusasisha kiotomatiki',
    moreFeatures: 'Vipengele zaidi',
    lowDataMode: 'Hali ya kutumia data kidogo', dailyTipsLabel: 'Vidokezo vya kila siku',
    clearCache: 'Futa akiba', cacheCleared: 'Akiba imefutwa',
    about: 'Kuhusu',
    aboutText: 'Programu bora ya hali ya hewa, iliyotengenezwa kwa muonekano wa kioo halisi na umakini wa hali ya juu. Data kutoka Open‑Meteo.',
    humidity: 'Unyevu', pressure: 'Shinikizo la hewa', wind: 'Upepo', gusts: 'Mkurupuko wa upepo', visibility: 'Uonekanaji',
    uvIndex: 'Kiwango cha UV', sunrise: 'Macheo', sunset: 'Machweo', dewPoint: 'Kiwango cha umande',
    airQuality: 'Ubora wa hewa', moonPhase: 'Awamu ya mwezi', rainChance: 'Uwezekano wa mvua',
    uvLow: 'Chini', uvModerate: 'Wastani', uvHigh: 'Juu', uvVeryHigh: 'Juu sana', uvExtreme: 'Kali',
    aqiGood: 'Nzuri', aqiFair: 'Wastani', aqiModerate: 'Kadiri', aqiPoor: 'Mbaya', aqiVeryPoor: 'Mbaya sana', aqiHazardous: 'Hatari',
    alertCyclone: 'Tahadhari ya kimbunga', alertSevereWind: 'Upepo mkali kupita kiasi', alertStrongWind: 'Upepo mkali',
    alertStorm: 'Dhoruba kali inakuja', alertHeavyRain: 'Mvua kubwa inatarajiwa',
    alertGustsUpTo: 'Mkurupuko wa upepo hadi km/h {n} unatarajiwa siku zijazo', alertDismiss: 'Funga',
    mistLabel: 'Ukungu hafifu', alertFog: 'Ukungu unapunguza uonekanaji', alertFromTime: 'Kuanzia {day} saa {time}',
    tipUmbrella: 'Chukua mwavuli leo', tipSunscreen: 'UV ni juu — tumia mafuta ya kujikinga na jua',
    tipWindy: 'Siku ya upepo, kuwa mwangalifu nje', tipCold: 'Kuna baridi — vaa nguo za joto', tipPleasant: 'Siku nzuri ya kutoka nje',
    home: 'Nyumbani', search: 'Tafuta', favorites: 'Vipendwa', settings: 'Mipangilio',
    addedFav: 'Imeongezwa kwenye vipendwa', removedFav: 'Imeondolewa kwenye vipendwa',
    shareLabel: 'Shiriki', shareGenerating: 'Inaandaa picha…', shareError: 'Imeshindwa kutengeneza picha',
    locateError: 'Imeshindwa kupata mahali ulipo.',
    shareSheetTitle: 'Shiriki hali ya hewa', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X (Twitter)', shareTelegram: 'Telegram', shareEmail: 'Barua pepe',
    shareCopyLink: 'Nakili maandishi', shareCopied: 'Imenakiliwa!', shareDownloadImg: 'Hifadhi picha', shareMoreApps: 'Programu zaidi', locateSettingsLabel: 'Tumia mahali ulipo sasa', locating: 'Inatafuta mahali…',
    loadError: 'Hakuna muunganisho. Inaonyesha data ya mwisho iliyopatikana.',
    noResults: 'Hakuna miji iliyopatikana.', currentLocation: 'Mahali pa sasa',
    today: 'Leo', tomorrow: 'Kesho',
    weekdays: ['Jumapili','Jumatatu','Jumanne','Jumatano','Alhamisi','Ijumaa','Jumamosi'],
    weekdaysShort: ['Jpl','Jtat','Jnne','Jtan','Alh','Ijm','Jmos'],
    months: ['Januari','Februari','Machi','Aprili','Mei','Juni','Julai','Agosti','Septemba','Oktoba','Novemba','Desemba'],
  },
  ru: {
    loading: 'Загрузка…', splashSub: 'готовим ваше небо…',
    searchPlaceholder: 'Поиск города…',
    feelsLike: 'Ощущается как',
    next24h: 'Следующие 24 часа', next7d: 'Прогноз на 7 дней', details: 'Подробности',
    tempChart: 'График температуры',
    dataSource: 'Данные предоставлены Open‑Meteo',
    updatedNow: 'Обновлено только что · нажмите для обновления',
    updatedAgo: 'Обновлено {n} мин. назад · нажмите для обновления',
    updating: 'Обновление…', refreshed: 'Данные обновлены', refreshFailed: 'Не удалось обновить сейчас',
    searchTitle: 'Поиск', searchSub: 'Узнайте погоду в любом городе мира',
    recentSearches: 'Недавние запросы',
    noRecents: 'Пока нет недавних запросов.',
    nowLabel: 'Сейчас',
    noData: 'Нет данных',
    favoritesTitle: 'Избранное', favoritesSub: 'Ваши сохранённые города',
    favEmpty: 'Пока нет избранных городов.',
    favEmptyHint: 'Нажмите на звезду на главном экране, чтобы сохранить город.',
    settingsTitle: 'Настройки', settingsSub: 'Персонализируйте свой опыт',
    tempUnit: 'Единица температуры', language: 'Язык', selectLanguage: 'Выбрать язык',
    theme: 'Тема', themeAuto: 'Авто', themeLight: 'Светлая', themeDark: 'Тёмная',
    allowLocation: 'Разрешить геолокацию', autoRefresh: 'Автообновление',
    moreFeatures: 'Дополнительные функции',
    lowDataMode: 'Режим экономии трафика', dailyTipsLabel: 'Ежедневные советы',
    clearCache: 'Очистить кэш', cacheCleared: 'Кэш очищен',
    about: 'О приложении',
    aboutText: 'Премиальное приложение погоды с настоящим эффектом матового стекла и вниманием к деталям. Данные предоставлены Open‑Meteo.',
    humidity: 'Влажность', pressure: 'Давление', wind: 'Ветер', gusts: 'Порывы', visibility: 'Видимость',
    uvIndex: 'УФ-индекс', sunrise: 'Восход', sunset: 'Закат', dewPoint: 'Точка росы',
    airQuality: 'Качество воздуха', moonPhase: 'Фаза луны', rainChance: 'Вероятность дождя',
    uvLow: 'Низкий', uvModerate: 'Умеренный', uvHigh: 'Высокий', uvVeryHigh: 'Очень высокий', uvExtreme: 'Экстремальный',
    aqiGood: 'Хорошее', aqiFair: 'Приемлемое', aqiModerate: 'Среднее', aqiPoor: 'Плохое', aqiVeryPoor: 'Очень плохое', aqiHazardous: 'Опасное',
    alertCyclone: 'Предупреждение о циклоне', alertSevereWind: 'Экстремальный ветер', alertStrongWind: 'Сильный ветер',
    alertStorm: 'Приближается сильная гроза', alertHeavyRain: 'Ожидается сильный дождь',
    alertGustsUpTo: 'В ближайшие дни ожидаются порывы до {n} км/ч', alertDismiss: 'Скрыть',
    mistLabel: 'Дымка', alertFog: 'Туман снижает видимость', alertFromTime: 'С {day} в {time}',
    tipUmbrella: 'Возьмите сегодня зонт', tipSunscreen: 'Высокий УФ — используйте солнцезащитный крем',
    tipWindy: 'Ветреный день, будьте осторожны на улице', tipCold: 'Холодно — одевайтесь теплее', tipPleasant: 'Приятный день для прогулки',
    home: 'Главная', search: 'Поиск', favorites: 'Избранное', settings: 'Настройки',
    addedFav: 'Добавлено в избранное', removedFav: 'Удалено из избранного',
    shareLabel: 'Поделиться', shareGenerating: 'Подготовка изображения…', shareError: 'Не удалось создать изображение',
    locateError: 'Не удалось определить ваше местоположение.',
    shareSheetTitle: 'Поделиться погодой', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X (Twitter)', shareTelegram: 'Telegram', shareEmail: 'Эл. почта',
    shareCopyLink: 'Копировать текст', shareCopied: 'Скопировано!', shareDownloadImg: 'Сохранить изображение', shareMoreApps: 'Другие приложения', locateSettingsLabel: 'Использовать текущее местоположение', locating: 'Определение местоположения…',
    loadError: 'Нет соединения. Показаны последние доступные данные.',
    noResults: 'Города не найдены.', currentLocation: 'Текущее местоположение',
    today: 'Сегодня', tomorrow: 'Завтра',
    weekdays: ['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'],
    weekdaysShort: ['Вс','Пн','Вт','Ср','Чт','Пт','Сб'],
    months: ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
  },
  hi: {
    loading: 'लोड हो रहा है…', splashSub: 'आपका आसमान तैयार हो रहा है…',
    searchPlaceholder: 'शहर खोजें…',
    feelsLike: 'महसूस होता है',
    next24h: 'अगले 24 घंटे', next7d: '7-दिन का पूर्वानुमान', details: 'विवरण',
    tempChart: 'तापमान चार्ट',
    dataSource: 'डेटा Open‑Meteo द्वारा प्रदान किया गया',
    updatedNow: 'अभी अपडेट किया गया · रीफ्रेश करने के लिए टैप करें',
    updatedAgo: '{n} मिनट पहले अपडेट किया गया · रीफ्रेश के लिए टैप करें',
    updating: 'रीफ्रेश हो रहा है…', refreshed: 'डेटा अपडेट हो गया', refreshFailed: 'अभी रीफ्रेश नहीं हो सका',
    searchTitle: 'खोजें', searchSub: 'दुनिया के किसी भी शहर का मौसम जानें',
    recentSearches: 'हाल की खोजें',
    noRecents: 'अभी तक कोई हालिया खोज नहीं है।',
    nowLabel: 'अभी',
    noData: 'कोई डेटा नहीं',
    favoritesTitle: 'पसंदीदा', favoritesSub: 'आपके सहेजे गए शहर',
    favEmpty: 'अभी तक कोई पसंदीदा शहर नहीं है।',
    favEmptyHint: 'शहर सहेजने के लिए होम स्क्रीन पर तारे को टैप करें।',
    settingsTitle: 'सेटिंग्स', settingsSub: 'अपने अनुभव को अनुकूलित करें',
    tempUnit: 'तापमान इकाई', language: 'भाषा', selectLanguage: 'भाषा चुनें',
    theme: 'थीम', themeAuto: 'ऑटो', themeLight: 'हल्का', themeDark: 'गहरा',
    allowLocation: 'लोकेशन की अनुमति दें', autoRefresh: 'ऑटो रीफ्रेश',
    moreFeatures: 'और सुविधाएँ',
    lowDataMode: 'लो डेटा मोड', dailyTipsLabel: 'दैनिक सुझाव',
    clearCache: 'कैश साफ़ करें', cacheCleared: 'कैश साफ़ हो गया',
    about: 'ऐप के बारे में',
    aboutText: 'असली फ्रॉस्टेड ग्लास इफ़ेक्ट और बारीकी पर ध्यान के साथ बना एक प्रीमियम मौसम ऐप। डेटा Open‑Meteo से।',
    humidity: 'नमी', pressure: 'दबाव', wind: 'हवा', gusts: 'तेज़ हवा के झोंके', visibility: 'दृश्यता',
    uvIndex: 'यूवी इंडेक्स', sunrise: 'सूर्योदय', sunset: 'सूर्यास्त', dewPoint: 'ओस बिंदु',
    airQuality: 'वायु गुणवत्ता', moonPhase: 'चंद्र कला', rainChance: 'बारिश की संभावना',
    uvLow: 'कम', uvModerate: 'मध्यम', uvHigh: 'उच्च', uvVeryHigh: 'बहुत उच्च', uvExtreme: 'अत्यधिक',
    aqiGood: 'अच्छी', aqiFair: 'ठीक', aqiModerate: 'मध्यम', aqiPoor: 'खराब', aqiVeryPoor: 'बहुत खराब', aqiHazardous: 'खतरनाक',
    alertCyclone: 'चक्रवात चेतावनी', alertSevereWind: 'अत्यधिक तेज़ हवा', alertStrongWind: 'तेज़ हवा',
    alertStorm: 'तेज़ आंधी-तूफान आ रहा है', alertHeavyRain: 'भारी बारिश की संभावना',
    alertGustsUpTo: 'अगले कुछ दिनों में {n} किमी/घंटा तक की हवाएँ चलने की संभावना', alertDismiss: 'बंद करें',
    mistLabel: 'हल्का कोहरा', alertFog: 'कोहरे से दृश्यता कम', alertFromTime: '{day} {time} बजे से',
    tipUmbrella: 'आज छाता साथ रखें', tipSunscreen: 'यूवी अधिक है — सनस्क्रीन लगाएं',
    tipWindy: 'हवा तेज़ है, बाहर सावधान रहें', tipCold: 'ठंड है — गर्म कपड़े पहनें', tipPleasant: 'बाहर जाने के लिए सुहावना दिन',
    home: 'होम', search: 'खोजें', favorites: 'पसंदीदा', settings: 'सेटिंग्स',
    addedFav: 'पसंदीदा में जोड़ा गया', removedFav: 'पसंदीदा से हटाया गया',
    shareLabel: 'साझा करें', shareGenerating: 'छवि तैयार हो रही है…', shareError: 'छवि नहीं बन सकी',
    locateError: 'आपका स्थान प्राप्त नहीं हो सका।',
    shareSheetTitle: 'मौसम साझा करें', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X (Twitter)', shareTelegram: 'Telegram', shareEmail: 'ईमेल',
    shareCopyLink: 'टेक्स्ट कॉपी करें', shareCopied: 'कॉपी हो गया!', shareDownloadImg: 'छवि सहेजें', shareMoreApps: 'और ऐप्स', locateSettingsLabel: 'वर्तमान स्थान का उपयोग करें', locating: 'स्थान ढूंढा जा रहा है…',
    loadError: 'कोई कनेक्शन नहीं। अंतिम उपलब्ध डेटा दिखाया जा रहा है।',
    noResults: 'कोई शहर नहीं मिला।', currentLocation: 'वर्तमान स्थान',
    today: 'आज', tomorrow: 'कल',
    weekdays: ['रविवार','सोमवार','मंगलवार','बुधवार','गुरुवार','शुक्रवार','शनिवार'],
    weekdaysShort: ['रवि','सोम','मंगल','बुध','गुरु','शुक्र','शनि'],
    months: ['जनवरी','फ़रवरी','मार्च','अप्रैल','मई','जून','जुलाई','अगस्त','सितंबर','अक्टूबर','नवंबर','दिसंबर'],
  },
  ja: {
    loading: '読み込み中…', splashSub: '空を準備しています…',
    searchPlaceholder: '都市を検索…',
    feelsLike: '体感温度',
    next24h: '今後24時間', next7d: '7日間の予報', details: '詳細',
    tempChart: '気温グラフ',
    dataSource: 'データ提供: Open‑Meteo',
    updatedNow: 'たった今更新 · タップして更新',
    updatedAgo: '{n}分前に更新 · タップして更新',
    updating: '更新中…', refreshed: 'データを更新しました', refreshFailed: '現在更新できません',
    searchTitle: '検索', searchSub: '世界中どの都市の天気でも検索できます',
    recentSearches: '最近の検索',
    noRecents: '最近の検索はまだありません。',
    nowLabel: '現在',
    noData: 'データなし',
    favoritesTitle: 'お気に入り', favoritesSub: '保存した都市',
    favEmpty: 'お気に入りの都市はまだありません。',
    favEmptyHint: 'ホーム画面の星をタップして都市を保存してください。',
    settingsTitle: '設定', settingsSub: '使い方をカスタマイズ',
    tempUnit: '温度の単位', language: '言語', selectLanguage: '言語を選択',
    theme: 'テーマ', themeAuto: '自動', themeLight: 'ライト', themeDark: 'ダーク',
    allowLocation: '位置情報を許可', autoRefresh: '自動更新',
    moreFeatures: 'その他の機能',
    lowDataMode: '低データモード', dailyTipsLabel: '毎日のヒント',
    clearCache: 'キャッシュを削除', cacheCleared: 'キャッシュを削除しました',
    about: 'このアプリについて',
    aboutText: '本物のすりガラス効果と細部へのこだわりで作られたプレミアム天気アプリ。データ提供: Open‑Meteo。',
    humidity: '湿度', pressure: '気圧', wind: '風速', gusts: '突風', visibility: '視程',
    uvIndex: 'UV指数', sunrise: '日の出', sunset: '日の入り', dewPoint: '露点',
    airQuality: '大気質', moonPhase: '月相', rainChance: '降水確率',
    uvLow: '低い', uvModerate: '中程度', uvHigh: '高い', uvVeryHigh: '非常に高い', uvExtreme: '極端に高い',
    aqiGood: '良好', aqiFair: 'まあまあ', aqiModerate: '中程度', aqiPoor: '悪い', aqiVeryPoor: '非常に悪い', aqiHazardous: '危険',
    alertCyclone: 'サイクロン警報', alertSevereWind: '猛烈な風', alertStrongWind: '強風',
    alertStorm: '激しい雷雨が接近中', alertHeavyRain: '大雨が予想されます',
    alertGustsUpTo: '今後数日で最大{n} km/hの突風が予想されます', alertDismiss: '閉じる',
    mistLabel: '霞', alertFog: '霧で視界が悪化', alertFromTime: '{day}の{time}から',
    tipUmbrella: '今日は傘を持って行きましょう', tipSunscreen: '紫外線が強いです — 日焼け止めを使用してください',
    tipWindy: '風が強い日です、屋外では注意してください', tipCold: '寒いです — 暖かい服装を', tipPleasant: '外出に気持ちの良い日です',
    home: 'ホーム', search: '検索', favorites: 'お気に入り', settings: '設定',
    addedFav: 'お気に入りに追加しました', removedFav: 'お気に入りから削除しました',
    shareLabel: '共有', shareGenerating: '画像を準備中…', shareError: '画像を作成できませんでした',
    locateError: '現在地を取得できませんでした。',
    shareSheetTitle: '天気を共有', shareWhatsapp: 'WhatsApp', shareFacebook: 'Facebook', shareTwitter: 'X（Twitter）', shareTelegram: 'Telegram', shareEmail: 'メール',
    shareCopyLink: 'テキストをコピー', shareCopied: 'コピーしました！', shareDownloadImg: '画像を保存', shareMoreApps: 'その他のアプリ', locateSettingsLabel: '現在地を使用', locating: '位置情報を取得中…',
    loadError: '接続がありません。最新の利用可能なデータを表示しています。',
    noResults: '都市が見つかりません。', currentLocation: '現在地',
    today: '今日', tomorrow: '明日',
    weekdays: ['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'],
    weekdaysShort: ['日','月','火','水','木','金','土'],
    months: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
  },
};

// -----------------------------------------------------------------------
// T() — tradução com fallback.
// Algumas funcionalidades novas (alerta de chuva, dicas contextuais,
// comparação histórica, modo offline) só têm texto traduzido em pt/en por
// agora. Para as restantes 10 línguas, T() recorre ao inglês em vez de
// mostrar undefined/a chave em bruto. Os textos "clássicos" da app
// continuam a usar I18N[lang][chave] diretamente, sem alterações.
// -----------------------------------------------------------------------
function T(lang, key, vars) {
  const dict = I18N[lang] || I18N.pt;
  let str = dict[key] ?? (I18N.en && I18N.en[key]) ?? (I18N.pt && I18N.pt[key]) ?? key;
  if (vars) {
    Object.keys(vars).forEach(k => { str = str.replace(`{${k}}`, vars[k]); });
  }
  return str;
}
