/* =========================================================================
   Aeris · config.js
   Constantes globais, endpoints e dicionário de traduções.
   ========================================================================= */

const CONFIG = {
  // Open-Meteo — API gratuita, sem chave necessária
  GEOCODE_URL: 'https://geocoding-api.open-meteo.com/v1/search',
  FORECAST_URL: 'https://api.open-meteo.com/v1/forecast',
  AIR_QUALITY_URL: 'https://air-quality-api.open-meteo.com/v1/air-quality',
  // Serviço gratuito de geocodificação inversa (sem chave), usado só para
  // obter o nome da cidade a partir de coordenadas do GPS.
  REVERSE_GEOCODE_URL: 'https://api.bigdatacloud.net/data/reverse-geocode-client',

  DEFAULT_CITY: { name: 'Quelimane', country: 'Moçambique', lat: -17.8786, lon: 36.8883, timezone: 'Africa/Maputo' },

  STORAGE_KEYS: {
    settings: 'aeris.settings',
    favorites: 'aeris.favorites',
    recents: 'aeris.recents',
    lastLocation: 'aeris.lastLocation',
    cache: 'aeris.cache',
    lastScreen: 'aeris.lastScreen'
  },

  AUTO_REFRESH_MS: 10 * 60 * 1000, // 10 minutos
  CACHE_TTL_MS: 10 * 60 * 1000,
};

const I18N = {
  pt: {
    loading: 'A carregar…',
    searchPlaceholder: 'Pesquisar cidade…',
    feelsLike: 'Sensação térmica de',
    next24h: 'Próximas 24 horas',
    next7d: 'Previsão para 7 dias',
    details: 'Detalhes',
    dataSource: 'Dados fornecidos por Open‑Meteo',
    updatedNow: 'Atualizado agora · toque para atualizar',
    updatedAgo: 'Atualizado há {n} min · toque para atualizar',
    updating: 'A atualizar…',
    refreshed: 'Dados atualizados',
    refreshFailed: 'Não foi possível atualizar agora',
    searchTitle: 'Pesquisar',
    searchSub: 'Encontre o clima de qualquer cidade do mundo',
    recentSearches: 'Pesquisas recentes',
    favoritesTitle: 'Favoritos',
    favoritesSub: 'As suas cidades guardadas',
    favEmpty: 'Ainda não tem cidades favoritas.',
    favEmptyHint: 'Toque na estrela no ecrã principal para guardar uma cidade.',
    settingsTitle: 'Configurações',
    settingsSub: 'Personalize a sua experiência',
    tempUnit: 'Unidade de temperatura',
    language: 'Idioma',
    theme: 'Tema',
    allowLocation: 'Permitir localização',
    autoRefresh: 'Atualização automática',
    humidity: 'Humidade',
    pressure: 'Pressão',
    wind: 'Vento',
    gusts: 'Rajadas',
    visibility: 'Visibilidade',
    uvIndex: 'Índice UV',
    sunrise: 'Nascer do sol',
    sunset: 'Pôr do sol',
    dewPoint: 'Ponto de orvalho',
    airQuality: 'Qualidade do ar',
    moonPhase: 'Fase da lua',
    rainChance: 'Prob. de chuva',
    home: 'Início', search: 'Pesquisar', favorites: 'Favoritos', settings: 'Ajustes',
    addedFav: 'Adicionada aos favoritos', removedFav: 'Removida dos favoritos',
    locateError: 'Não foi possível obter a sua localização.',
    loadError: 'Sem ligação. A mostrar os últimos dados disponíveis.',
    noResults: 'Nenhuma cidade encontrada.',
    currentLocation: 'Localização atual',
    today: 'Hoje', tomorrow: 'Amanhã',
    weekdays: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
    weekdaysShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'],
    months: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
  },
  en: {
    loading: 'Loading…',
    searchPlaceholder: 'Search city…',
    feelsLike: 'Feels like',
    next24h: 'Next 24 hours',
    next7d: '7-day forecast',
    details: 'Details',
    dataSource: 'Data provided by Open‑Meteo',
    updatedNow: 'Updated just now · tap to refresh',
    updatedAgo: 'Updated {n} min ago · tap to refresh',
    updating: 'Refreshing…',
    refreshed: 'Data refreshed',
    refreshFailed: 'Could not refresh right now',
    searchTitle: 'Search',
    searchSub: 'Find the weather for any city in the world',
    recentSearches: 'Recent searches',
    favoritesTitle: 'Favorites',
    favoritesSub: 'Your saved cities',
    favEmpty: 'No favorite cities yet.',
    favEmptyHint: 'Tap the star on the home screen to save a city.',
    settingsTitle: 'Settings',
    settingsSub: 'Personalize your experience',
    tempUnit: 'Temperature unit',
    language: 'Language',
    theme: 'Theme',
    allowLocation: 'Allow location',
    autoRefresh: 'Auto refresh',
    humidity: 'Humidity',
    pressure: 'Pressure',
    wind: 'Wind',
    gusts: 'Gusts',
    visibility: 'Visibility',
    uvIndex: 'UV Index',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    dewPoint: 'Dew point',
    airQuality: 'Air quality',
    moonPhase: 'Moon phase',
    rainChance: 'Rain chance',
    home: 'Home', search: 'Search', favorites: 'Favorites', settings: 'Settings',
    addedFav: 'Added to favorites', removedFav: 'Removed from favorites',
    locateError: 'Could not get your location.',
    loadError: 'No connection. Showing the last available data.',
    noResults: 'No cities found.',
    currentLocation: 'Current location',
    today: 'Today', tomorrow: 'Tomorrow',
    weekdays: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
    weekdaysShort: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
  }
};
